name: Lint

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
      - uses: akaihola/darker@1.7.0
        with:
          options: "-r main --check --diff --isort --color"
          src: "."
          version: "~=1.7.0"
          lint: "flake8,pylint==2.13.1"
